import Head from "next/head";
import Cart from "../components/Cart";
import Navbar from "@components/Navbar";
import Food from "@components/Food";
import { v2 } from "@assets/photos/foods";
import KabsahiCover from "@assets/kabsahi-cover.png";
import Image from "next/image";
import Footer from "@components/Footer";
import FoodOptions from "@components/FoodOptions";

import { useDispatch, useSelector } from "react-redux";
import IStoreReducer from "@redux/IStoreReducer";
import BestSellers from "@components/Food/BestSellers";
import FoodMenu from "@components/Food/FoodMenu";
import { IoLocationOutline } from "react-icons/io5";
import Kabsa from "@assets/photos/kabsa2.png";
import Location from "@components/Location";

export default function Home() {
  const {
    foodOptions: { isOpened },
  } = useSelector((state: IStoreReducer) => state._foodReducer);

  return (
    <>
      <Head>
        <title>Kabsahi - Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isOpened && <FoodOptions />}

      <Cart />

      <div className="relative flex min-h-screen flex-col items-center justify-start overflow-hidden bg-white">
        <div className="relative flex w-full flex-col items-center">
          <div className="absolute h-full w-full bg-gradient-to-t from-black/40 to-black/80" />
          <Image src={Kabsa} alt="" className="w-full min-w-[1300px]" />
          <Navbar />
          <div className="absolute bottom-[-150px] flex h-full w-full items-end justify-center p-2 sm:bottom-[-100px]">
            <Location />
          </div>
        </div>
        <div className="h-[200px] sm:h-[150px]"></div>
        <div className="z-20 flex w-full flex-col items-center justify-center">
          <BestSellers />
          <div className="my-6"></div>
          <FoodMenu />
          <hr />

          <div className="m-12 flex flex-col justify-center">
            {/* <span className=" mx-4 my-8 text-center text-xl font-bold text-dominant">
              OPEN FOR FRANCHISE
            </span> */}
            <Image src={KabsahiCover} alt="Kabsahi Cover" width={600}></Image>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}
