import Head from "next/head";
import Cart from "../components/Cart";
import Navbar from "@components/Navbar";
import Food from "@components/Food";
import { v2 } from "@assets/photos/foods";
import KabsahiCover from "@assets/kabsahi-cover.png";
import Image from "next/image";
import Footer from "@components/Footer";
import FoodOptions from "@components/FoodOptions";

import { useDispatch, useSelector } from "react-redux";
import IStoreReducer from "@redux/IStoreReducer";

export default function Home() {
  const {
    foods,
    foodOptions: { isOpened },
  } = useSelector((state: IStoreReducer) => state._foodReducer);

  return (
    <>
      <Head>
        <title>Kabsahi - Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isOpened && <FoodOptions />}
      <div className="relative flex min-h-screen flex-col justify-start overflow-hidden bg-white">
        <Navbar />
        <Cart />

        <div className="my-8 flex flex-col items-center">
          <div className="flex justify-center px-2">
            <Image src={KabsahiCover} alt="Kabsahi Cover" width={600}></Image>
          </div>
          <div className="my-8">
            {/* <div className="my-4">
              <h1 className="mx-4 my-8 text-2xl font-bold">Best Sellers 😊</h1>
              <div className="flex max-w-[820px] flex-wrap items-center justify-center">
                <Food
                  name="Chicken Kabsa (Budget Meal)"
                  img={v2.KabsaBudgetMeal}
                />
                <Food name="Shawarma Wraps" img={v2.Shawarma} />
                <Food name="Sambousak" img={v2.Sambousak} />
                <Food name="Broasted Series" img={v2.BroastedChicken} />
              </div>
            </div> */}
            <div className="my-4">
              <h1 className="mx-4 my-8 text-xl font-bold">Food Menu 🍴</h1>
              <div className="flex max-w-[820px] flex-wrap items-center justify-center">
                {foods.map((e, i) => {
                  return (
                    <Food
                      key={i}
                      name={e.foodName}
                      code={e.foodCode}
                      img={e.img}
                    />
                  );
                })}
                {foods.map((e, i) => {
                  return (
                    <Food
                      key={i}
                      name={e.foodName}
                      code={e.foodCode}
                      img={e.img}
                    />
                  );
                })}
                {/* <Food name="Biryani Series" img={v2.Baryani} />
                <Food name="Broasted Series" img={v2.BroastedChicken} />
                <Food
                  name="Chicken Kabsa (Budget Meal)"
                  img={v2.KabsaBudgetMeal}
                />
                <Food name="Kabsa Platter" img={v2.KabsahiPlatter} />
                <Food name="Sambousak" img={v2.Sambousak} />
                <Food name="Shawarma Rice" img={v2.ShawarmaRice} />
                <Food name="Shawarma Wraps" img={v2.Shawarma} />
                <Food /> */}
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}
